multi_gpu: False

model_name: RPPformer-Flow

arch: Transformer
last_relu: False
allow_less_points: False

# general args
pretrain: #

dim: 3
num_points: 8192

DEVICE: cuda

evaluate: True
resume: True

dataset: KITTI
#FlyingThings3DSubset
#KITTI
data_root: #

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# data augmentation
aug_together:
  degree_range: 0.1745329252
  shift_range: 1.
  scale_low: 0.95
  scale_high: 1.05
  jitter_sigma: 0.01
  jitter_clip: 0.00

aug_pc2:
  degree_range: 0.
  shift_range: 0.3
  jitter_sigma: 0.01
  jitter_clip: 0.00

# miscalleneous
workers: 16








